version: '3'

services:

  db:
    image: mysql:5.7
    container_name: locoform-db
    environment:
      - MYSQL_USER=locoform_user
      - MYSQL_PASSWORD=locoform_pwd
      - MYSQL_DATABASE=locoform
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_ONETIME_PASSWORD=0
    command: --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION --max_allowed_packet=32505856000 --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"

  web:
    image: php:7-apache
    command: >
      bash -c "a2enmod rewrite
      && docker-php-ext-install pdo_mysql
      && apache2-foreground"
    container_name: locoform-web
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./:/var/www/
      - ./docker/apache-config:/etc/apache2/sites-enabled/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: locoform-db-admin
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_USER: locoform_user
      MYSQL_PASSWORD: locoform_pwd
      MYSQL_DATABASE: locoform
