version: '3'

services:
  web:
    image: php:7-apache
    container_name: locoform-web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/
      - ./docker/apache-config:/etc/apache2/sites-enabled/
